from pydantic import BaseModel, Field, field_validator
from typing import Optional, Dict, Any

class TelemetryEvent(BaseModel):
    """
    Data model representing a crash or error intercepted from the telemetry layer.
    """
    event_id: str
    service_name: str
    crash_log: str = Field(description="The stack trace or error log of the crash.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context like memory usage or pod name.")

class PatchProposal(BaseModel):
    """
    A strictly typed patch proposed by the Executor Agent (Hermes).
    """
    file_path: str = Field(description="The strictly relative path to the file to be patched.")
    target_content: str = Field(description="The exact chunk of code to replace.")
    replacement_content: str = Field(description="The new code to insert.")
    root_cause_analysis: str = Field(description="Explicitly state the exact line of code that failed and the root cause.")
    explanation: str = Field(description="A brief explanation of why this fixes the issue.")

    @field_validator('file_path')
    @classmethod
    def validate_file_path(cls, v: str) -> str:
        if ".." in v or v.startswith("/"):
            raise ValueError("Path traversal detected. file_path must be strictly relative to the repository root and cannot contain '..'")
        return v

class SecurityReview(BaseModel):
    """
    A strictly typed review generated by the Reviewer Agent (Nemotron).
    """
    is_safe: bool = Field(description="True if the patch is safe and logically sound.")
    vulnerability_found: bool = Field(description="True if a CVE or malicious payload is detected.")
    feedback: str = Field(description="Feedback or reasons for rejection.")
